### PR TITLE
Always use for-of statements for legacy iterator support

### PR DESCRIPTION
**Pull request by falsandtru**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
I'm not sure I understand - all of this detection is absolutely critical for some  browsers where `for..of` is the only way to iterate a set.

**Comment by JakeChampion** [comment]
I believe @falsandtru is stating that if a browser has `@@iterator` support, it would be iterable via `for...of`, making this code redundant.

**Comment by ljharb** [comment]
hmm, that's interesting. I'll have to think about this.

**Comment by falsandtru** [comment]
@JakeChampion Thanks. Additionally, more legacy firefox (17-26) uses `iterator` property. Legacy safari's Map/Set can iterate only by for-of. These differences are too complex. for-of would resolve all iterations.

**Pull request closed without merging**
