### PR TITLE
Fix the iterator support for legacy collection

### PR DESCRIPTION
**Pull request by falsandtru**

### CODE REVIEW

**Comment by falsandtru** [comment]
At least, these checks won't work with Firefox 13-19 because these versions have Map, but don't have Map.prototype.entiries. This pr works as a partial fix of #41. So this pr will resolve cloud test failures of #41.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by ljharb** [comment]
Sounds good. (Do they have `Map#forEach`?)

**Comment by falsandtru** [comment]
They have it from FF25. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach

**Comment by ljharb** [comment]
Is there any way to iterate a Map in Firefox 13-19?

**Comment by falsandtru** [comment]
Map is iterable from Firefox 17, and it possibly can iterate using for-of. https://github.com/mathiasbynens/Array.from/issues/41#issuecomment-250935550

**Comment by JakeChampion** [comment]
I ran this on a bunch of firefox browsers (46 in total), the tests failed in 11 of them.

Here is the [results](https://gist.github.com/JakeChampion/5315c81525d0e81f6236ea7f7ac6ed88#file-firefox_results-txt) and here is just the [errors](https://gist.github.com/JakeChampion/5315c81525d0e81f6236ea7f7ac6ed88#file-firefox_errors-txt).

The browsers which fail are:
firefox 13
firefox 14
firefox 15
firefox 16
firefox 20
firefox 21
firefox 22
firefox 23
firefox 24
firefox 25
firefox 26

**Comment by ljharb** [comment]
@JakeChampion thanks! if it's easy, could you run the same tests on master? i suspect they won't all pass there yet.

**Comment by JakeChampion** [comment]
@ljharb Sure thing, would you like only firefox or other browsers as well?

**Comment by falsandtru** [comment]
@JakeChampion Thanks for testing! Just to clarify, is this a regression (tests are passed on master branch) ?

**Comment by JakeChampion** [comment]
Running on master now @falsandtru

**Comment by JakeChampion** [comment]
These browsers fail on master:
firefox 14
firefox 13
firefox 16
firefox 15
firefox 20
firefox 21
firefox 22
firefox 23
firefox 24
firefox 25
firefox 26

Here are the failure results -- https://gist.github.com/JakeChampion/364bec6361989d0c0945fbf93db5f674

**Comment by falsandtru** [comment]
Thanks again. Seems like this patch has no impact. I think we can fix these failures after merging this patch. And #44 would fix some failures.

**Pull request merged**
